### ISSUE TITLE
No pufferfish emoji support

### ISSUE THREAD

**Issue by cassiereuter** [anadolski/apytl#1]
Hi there, mighty developer!  Could you please make the pufferfish emoji 🐡 a standard emoji? Thanks!

**Comment by anadolski** [comment]
Hello, kind user.

The pufferfish is now a standard emoji as of release 0.0a5, which is live on PyPI. You can access the pufferfish by passing `fill='pufferfish'` to `apytl.drawbar()`.

Closing this ticket.
